#!/bin/bash
# Generate F-PIN-A GWDG retrain RunJobs for every paper cell.
# F-PIN-A = F-PIN attention encoder + PIM 2022's MTSPSoftassign head
# (faithfully ported from models/PIMold/src/utils_all/softassign.py).
# Structural feasibility prior at head: out-flow + in-flow per-customer
# uniqueness. Lever for matching PIM's 0% fleet violation at scale.
set -euo pipefail

PROJ=${PROJ:-/projects/extern/nhr/nhr_ni/nim00026/dir.project/daniela}
TARGET_ROOT=${TARGET_ROOT:-$PROJ/data/train_data/cvrp/uniform/targets/fc_hgs_clean}

target_dir_for() {
  local n=$1; local m=$2
  case "${n}_${m}" in
    20_3)   printf '%s/n20_k3'  "$TARGET_ROOT" ;;
    20_4)   printf '%s/n20_k4'  "$TARGET_ROOT" ;;
    50_6)   printf '%s/n50_k6'  "$TARGET_ROOT" ;;
    50_7)   printf '%s/n50_k7'  "$TARGET_ROOT" ;;
    60_6)   printf '%s/n60_k6'  "$TARGET_ROOT" ;;
    60_7)   printf '%s/n60_k7'  "$TARGET_ROOT" ;;
    60_9)   printf '%s/data/train_data/cvrp/uniform/targets/converted_npz' "$PROJ" ;;
    100_9)  printf '%s/n100_k9' "$TARGET_ROOT" ;;
    100_10) printf '%s/n100_k10' "$TARGET_ROOT" ;;
    *) echo "No mapping for N=${n} M=${m}" >&2; return 1 ;;
  esac
}

batch_for() {
  case "${1}_${2}" in
    100_10) printf '32' ;;
    *)      printf '64' ;;
  esac
}

gen() {
  local n=$1; local m=$2
  local name="GWDG_FPIN_A_N${n}_M${m}"
  local targets bs
  targets=$(target_dir_for "$n" "$m")
  bs=$(batch_for "$n" "$m")

  cat > "RunJob_${name}.sh" <<EOF
#!/bin/bash
# Auto-generated by generate_gwdg_fpin_a_runjobs.sh
# F-PIN-A retrain: attention encoder + PIM 2022 MTSPSoftassign head.
# softassign_head=True + softassign_layers=3 + sinkhorn_assignment=False.
#SBATCH --job-name=${name}
#SBATCH --partition=grete:shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -G A100:1
#SBATCH --time=48:00:00
#SBATCH --requeue
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=thyssens@ismll.de
#SBATCH --output=${PROJ}/cluster_logs/${name}_%j.log
#SBATCH --error=${PROJ}/cluster_logs/${name}_%j.err

set -eo pipefail
mkdir -p "${PROJ}/cluster_logs"
source "\${HOME}/miniconda3/etc/profile.d/conda.sh"
conda activate l2o_py310
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export FPIN_OUTPUT_ROOT="${PROJ}/fpin_outputs"
mkdir -p "\${FPIN_OUTPUT_ROOT}"
REPO=\${REPO:-\${SLURM_SUBMIT_DIR:-\$HOME/repos/fpin}}
cd "\${REPO}"

RUN_NAME="fpin_a_n${n}_k${m}_unf_attn"
RESUME_GLOB="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_*/checkpoints/best.pt"
LATEST_CKPT=\$(ls -t \$RESUME_GLOB 2>/dev/null | head -1 || true)
RUN_DIR="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_\$(date +%Y-%m-%d_%H-%M-%S)"

COMMON_ARGS=( \\
  env=cvrp${n}_unf model=fpin hydra.job.chdir=true \\
  "hydra.run.dir=\${RUN_DIR}" \\
  model_cfg.model_args.max_fleet_length=${m} model_cfg.model_args.fleet_in_dim=260 \\
  model_cfg.model_args.use_attn=True model_cfg.model_args.vehicle_cond_edge_head=True \\
  model_cfg.model_args.sinkhorn_assignment=False \\
  model_cfg.model_args.joint_customer_norm=False \\
  model_cfg.model_args.softassign_head=True \\
  model_cfg.model_args.softassign_layers=3 \\
  model_cfg.model_args.add_demand_weights=True \\
  loss_cfg.start_weight=0.2 loss_cfg.pen_w=0.1 loss_cfg.load_w=0.2 \\
  train_cfg.batch_size=${bs} train_cfg.n_epochs=200 train_cfg.lr=0.0001 train_cfg.checkpoint_epochs=50 \\
  "train_cfg.run_name=\${RUN_NAME}" \\
  fixed_train_set=${targets}/ \\
)

if [ -n "\${LATEST_CKPT:-}" ] && [ -f "\${LATEST_CKPT}" ]; then
  echo "[RESUME] \$LATEST_CKPT"
  srun python run_fpin.py meta=resume \\
    test_cfg.checkpoint_load_path="\${LATEST_CKPT}" \\
    "\${COMMON_ARGS[@]}"
else
  echo "[FRESH] No prior \${RUN_NAME} ckpt; training from scratch."
  srun python run_fpin.py meta=train_base "\${COMMON_ARGS[@]}"
fi
EOF
  echo "wrote RunJob_${name}.sh"
}

gen 20 3
gen 20 4
gen 50 6
gen 50 7
gen 60 6
gen 60 7
gen 60 9
gen 100 9
gen 100 10
