#!/bin/bash
# Generate F-PIN-G GWDG retrain RunJobs.
# F-PIN-G = F-PIN attention encoder + vehicle-conditioned MLP edge head, but with
# PIM 2022's OUTPUT NORMALIZATION: one softmax over all n*n edges per vehicle
# (global_edge_softmax). This is a clean ONE-variable change vs F-PIN-AB (which uses
# the iterative log-domain softassign head): same encoder, same head, same loss weights,
# ONLY the head normalization differs. Motivation (2026-06-04): decode-eval of the
# architecture ablations showed fewer softassign iters -> better Cost_v/feasibility, and
# the provenance analysis showed PIM's committed global-edge softmax (row_H 0.12 vs F-PIN
# 0.51) is the dominant heatmap-quality difference and the one model-side lever never tested.
set -euo pipefail

PROJ=${PROJ:-/projects/extern/nhr/nhr_ni/nim00026/dir.project/daniela}
TARGET_ROOT=${TARGET_ROOT:-$PROJ/data/train_data/cvrp/uniform/targets/fc_hgs_clean}

target_dir_for() {
  local n=$1; local m=$2
  case "${n}_${m}" in
    20_3)   printf '%s/n20_k3'  "$TARGET_ROOT" ;;
    20_4)   printf '%s/n20_k4'  "$TARGET_ROOT" ;;
    50_6)   printf '%s/n50_k6'  "$TARGET_ROOT" ;;
    50_7)   printf '%s/n50_k7'  "$TARGET_ROOT" ;;
    100_9)  printf '%s/n100_k9' "$TARGET_ROOT" ;;
    100_10) printf '%s/n100_k10' "$TARGET_ROOT" ;;
    *) echo "No mapping for N=${n} M=${m}" >&2; return 1 ;;
  esac
}

start_weight_for() { case "$1" in 100) printf '0.5' ;; *) printf '0.2' ;; esac; }
batch_for() {
  case "${1}_${2}" in
    100_10) printf '32' ;;
    100_9)  printf '32' ;;
    *)      printf '64' ;;
  esac
}

gen() {
  local n=$1; local m=$2
  local name="GWDG_FPIN_G_N${n}_M${m}"
  local targets bs sw
  targets=$(target_dir_for "$n" "$m")
  bs=$(batch_for "$n" "$m"); sw=$(start_weight_for "$n")

  cat > "RunJob_${name}.sh" <<EOF
#!/bin/bash
# Auto-generated by generate_gwdg_fpin_g_runjobs.sh
# F-PIN-G: F-PIN attention encoder + vehicle-cond MLP edge head + PIM-2022 GLOBAL-EDGE
# softmax normalization (one softmax over all n*n edges per vehicle). softassign_head=False,
# global_edge_softmax=True. Loss consumes pre-normalized log-probs (loss_cfg.global_edge_softmax).
#SBATCH --job-name=${name}
#SBATCH --partition=grete:shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -G A100:1
#SBATCH --time=48:00:00
#SBATCH --requeue
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=thyssens@ismll.de
#SBATCH --output=${PROJ}/cluster_logs/${name}_%j.log
#SBATCH --error=${PROJ}/cluster_logs/${name}_%j.err

set -eo pipefail
mkdir -p "${PROJ}/cluster_logs"
source "\${HOME}/miniconda3/etc/profile.d/conda.sh"
conda activate l2o_py310
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export FPIN_OUTPUT_ROOT="${PROJ}/fpin_outputs"
mkdir -p "\${FPIN_OUTPUT_ROOT}"
REPO=\${REPO:-\${SLURM_SUBMIT_DIR:-\$HOME/repos/fpin}}
cd "\${REPO}"

RUN_NAME="fpin_g_n${n}_k${m}_unf_attn"
RESUME_GLOB="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_*/checkpoints/best.pt"
LATEST_CKPT=\$(ls -t \$RESUME_GLOB 2>/dev/null | head -1 || true)
RUN_DIR="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_\$(date +%Y-%m-%d_%H-%M-%S)"

COMMON_ARGS=( \\
  env=cvrp${n}_unf model=fpin hydra.job.chdir=true \\
  "hydra.run.dir=\${RUN_DIR}" \\
  model_cfg.model_args.max_fleet_length=${m} model_cfg.model_args.fleet_in_dim=260 \\
  model_cfg.model_args.use_attn=True model_cfg.model_args.vehicle_cond_edge_head=True \\
  model_cfg.model_args.sinkhorn_assignment=False \\
  model_cfg.model_args.joint_customer_norm=False \\
  model_cfg.model_args.softassign_head=False \\
  model_cfg.model_args.global_edge_softmax=True \\
  model_cfg.model_args.add_demand_weights=True \\
  loss_cfg.start_weight=${sw} loss_cfg.pen_w=0.1 loss_cfg.load_w=0.2 \\
  train_cfg.batch_size=${bs} train_cfg.n_epochs=200 train_cfg.lr=0.0001 train_cfg.checkpoint_epochs=50 \\
  "train_cfg.run_name=\${RUN_NAME}" \\
  fixed_train_set=${targets}/ \\
)

if [ -n "\${LATEST_CKPT:-}" ] && [ -f "\${LATEST_CKPT}" ]; then
  echo "[RESUME] \$LATEST_CKPT"
  srun python run_fpin.py meta=resume \\
    test_cfg.checkpoint_load_path="\${LATEST_CKPT}" \\
    "\${COMMON_ARGS[@]}"
else
  echo "[FRESH] No prior \${RUN_NAME} ckpt; training from scratch."
  srun python run_fpin.py meta=train_base "\${COMMON_ARGS[@]}"
fi
EOF
  echo "wrote RunJob_${name}.sh"
}

gen 20 3
gen 20 4
gen 50 6
gen 50 7
gen 100 9
gen 100 10
