#!/bin/bash

set -euo pipefail

# Generate GWDG retrain scripts with explicit target mappings.
# Most jobs use corrected clean FC-CVRP HGS targets.
# The legacy N=60, M=9 job intentionally stays on the old converted_npz source.

PROJ=${PROJ:-/projects/extern/nhr/nhr_ni/nim00026/dir.project/daniela}
TARGET_ROOT=${TARGET_ROOT:-$PROJ/data/train_data/cvrp/uniform/targets/fc_hgs_clean}

target_dir_for() {
  local n=$1
  local m=$2
  case "${n}_${m}" in
    20_3)  printf '%s/n20_k3' "$TARGET_ROOT" ;;
    20_4)  printf '%s/n20_k4' "$TARGET_ROOT" ;;
    50_6)  printf '%s/n50_k6' "$TARGET_ROOT" ;;
    50_7)  printf '%s/n50_k7' "$TARGET_ROOT" ;;
    60_6)  printf '%s/n60_k6' "$TARGET_ROOT" ;;
    60_7)  printf '%s/n60_k7' "$TARGET_ROOT" ;;
    60_9)  printf '%s/data/train_data/cvrp/uniform/targets/converted_npz' "$PROJ" ;;
    100_9) printf '%s/n100_k9' "$TARGET_ROOT" ;;
    100_10) printf '%s/n100_k10' "$TARGET_ROOT" ;;
    *)
      echo "No target-dir mapping defined for N=${n}, M=${m}" >&2
      return 1
      ;;
  esac
}

# Per-cell batch size override. N=100,M=10 OOMs at batch=64 on A100-40GB
# (dense loss expansion in fpin/VRP_Loss1.py:159).
batch_for() {
  case "${1}_${2}" in
    100_10) printf '32' ;;
    *)      printf '64' ;;
  esac
}

gen() {
  local n=$1
  local m=$2
  local name="GWDG_E3_N${n}_M${m}"
  local targets
  targets=$(target_dir_for "$n" "$m")
  local bs
  bs=$(batch_for "$n" "$m")

  cat > "RunJob_${name}.sh" <<EOF
#!/bin/bash
# Auto-generated by generate_gwdg_runjobs.sh
# fixed_train_set=${targets}
# $( [ "${n}_${m}" = "60_9" ] && printf 'Note: N=60,M=9 intentionally uses the legacy converted_npz targets.' )
#SBATCH --job-name=${name}
#SBATCH --partition=grete:shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -G A100:1
#SBATCH --time=48:00:00
#SBATCH --requeue
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=thyssens@ismll.de
#SBATCH --output=${PROJ}/cluster_logs/${name}_%j.log
#SBATCH --error=${PROJ}/cluster_logs/${name}_%j.err

set -eo pipefail
mkdir -p "${PROJ}/cluster_logs"
source "\${HOME}/miniconda3/etc/profile.d/conda.sh"
conda activate l2o_py310
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# Write Hydra outputs (checkpoints + logs) to project storage, not \$HOME.
# config/config.yaml resolves hydra.run.dir via \${oc.env:FPIN_OUTPUT_ROOT,outputs}.
export FPIN_OUTPUT_ROOT="${PROJ}/fpin_outputs"
mkdir -p "\${FPIN_OUTPUT_ROOT}"
# NOTE: under sbatch the script is copied to /var/spool/slurmd/job<id>/, so
# dirname \${BASH_SOURCE[0]} resolves to the spool dir (NOT the repo) and srun
# then cannot find run_fpin.py. Use SLURM_SUBMIT_DIR (the directory sbatch was
# invoked from) with a hardcoded fallback, never BASH_SOURCE.
REPO=\${REPO:-\${SLURM_SUBMIT_DIR:-\$HOME/repos/fpin}}
cd "\${REPO}"

# Auto-resume: scope the resume glob to THIS cell's run_name so we never
# pick up a ckpt from a different (N, M) by accident. Latest-mtime wins.
RUN_NAME="fpin_e3_n${n}_k${m}_unf_attn"
RESUME_GLOB="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_*/checkpoints/best.pt"
LATEST_CKPT=\$(ls -t \$RESUME_GLOB 2>/dev/null | head -1 || true)

# Force a unique hydra.run.dir per cell so simultaneous starts at the same
# second can't share a directory (the bug behind the May 30 N50/N60 collisions).
RUN_DIR="\${FPIN_OUTPUT_ROOT}/cvrp_${n}_uniform/train/fpin/\${RUN_NAME}_\$(date +%Y-%m-%d_%H-%M-%S)"

COMMON_ARGS=( \\
  env=cvrp${n}_unf model=fpin hydra.job.chdir=true \\
  "hydra.run.dir=\${RUN_DIR}" \\
  model_cfg.model_args.max_fleet_length=${m} model_cfg.model_args.fleet_in_dim=260 \\
  model_cfg.model_args.use_attn=True model_cfg.model_args.vehicle_cond_edge_head=True \\
  model_cfg.model_args.sinkhorn_assignment=True model_cfg.model_args.sinkhorn_iters=3 \\
  train_cfg.batch_size=${bs} train_cfg.n_epochs=200 train_cfg.lr=0.0001 train_cfg.checkpoint_epochs=10 \\
  "train_cfg.run_name=\${RUN_NAME}" \\
  fixed_train_set=${targets}/ \\
)

if [ -n "\${LATEST_CKPT:-}" ] && [ -f "\${LATEST_CKPT}" ]; then
  echo "[RESUME] Found prior checkpoint: \${LATEST_CKPT}"
  srun python run_fpin.py \\
    meta=resume \\
    test_cfg.checkpoint_load_path="\${LATEST_CKPT}" \\
    "\${COMMON_ARGS[@]}"
else
  echo "[FRESH] No prior checkpoint under \${RESUME_GLOB}; training from scratch"
  srun python run_fpin.py \\
    meta=train_base \\
    "\${COMMON_ARGS[@]}"
fi
EOF

  echo "wrote RunJob_${name}.sh"
}

gen 20 3
gen 20 4
gen 50 6
gen 50 7
gen 60 6
gen 60 7
gen 60 9
gen 100 9
gen 100 10
